services:
  - type: web
    name: metabase-deploy
    env: image
    plan: free
    autoDeploy: true
    image:
      url: metabase/metabase:latest
    envVars:
      - key: MB_JETTY_PORT
        value: "3000"
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx350m"
    ports:
      - port: 3000
        protocol: tcp
